### ISSUE TITLE
Fails to parse `<stdint.h>`-style integer types

### ISSUE THREAD

**Issue by mincrmatt12** [fox-it/dissect.cstruct_legacy#3]
When given a struct using the definitions found in `<stdint.h>` (e.g `uint16_t`), the library complains about an unknown type.

**Comment by Beercow** [comment]
You could add it with:
addtype(name, type)

If it is the same as uint16, you could use that also.

**Comment by Schamper** [comment]
You can also define it in your definition:
```
In [1]: from dissect import cstruct

In [2]: c = cstruct.cstruct()

In [3]: c.load("""
   ...: typedef uint16 uint16_t;
   ...: """)

In [4]: c.uint16_t == c.uint16
Out[4]: True
```
